### ISSUE TITLE
After adding the NativeRouter, the browser side rendering has corrupted.

### ISSUE THREAD

**Issue by sahilrajput03** [Kaltsoon/react-native-material#10]
Since, I now know that NativeRouter can't be used for web, rather we'd need to use  react-router-dom for the router. So, I looked up on youtube,github,stackoverflow for using same codebase for this, but it didn't workout for me. What I got to know is, there must be separate components/modules from which react-native can automatically import android and web and ios files, I found the documentation help for it here.. 
[Link](http://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page)
But still I'm facing the same issue, browser throws this error.., just after adding <Router>...</Router>.(I have renamed NativeRouter to Router in comp.android.js) and importing that to App.js file. Please suggest something to try..,how to solve this. Link to repo: [My repo](https://github.com/sahilrajput03/rate-repository-app)
![image](https://user-images.githubusercontent.com/31458531/89824461-c370ef80-db70-11ea-8399-49a92728506c.png)

**Comment by Kaltsoon** [comment]
That's true. However, I haven't figured out a way to fix this yet. Importing a different router based on the build environment could be one escape hatch to fix this issue

**Comment by Kaltsoon** [comment]
This could be a great example in the "Platform specific code" section. Maybe something like this would work:

`Router.web.jsx`:

```javascript
import { MemoryRouter } from 'react-router-dom';

export default MemoryRouter;
```

`Router.native.jsx`:

```javascript
import { NativeRouter } from 'react-router-native';

export default NativeRouter;
```

**Comment by sahilrajput03** [comment]
Hey, actually I searched this error on google, and I figured it out i was doing a typo in comp.web.js file, which is imported by react-native on web paltform, 
like:
```export { BrowserRouter as Router, Route, Switch, Redirect, Link } from 'react-router-dom';
// ────────────────────────────────────────────────────────
// Earlier it was like below line-
export { Router, Route, Switch, Redirect, Link } from 'react-router-dom';```
Now, I don't see any error/warning in terminal, and its RESOLVED for web.
I guess course content for using platform based components/modules like:- componentName.android, omponentName.ios.js, omponentName.web.js  is needed to be addded.
Its illustrated here: [react-native-web docs - multi platform](http://necolas.github.io/react-native-web/docs/?path=/docs/guides-multi-platform--page).
Thanks.

**Comment by Kaltsoon** [comment]
Yes, creating an `Router.web.jsx` and `Router.native.jsx` with exports from either `react-router-dom` or `react-router-native` seems to work. E.g. `Router.web.jsx`:

```javascript
import { MemoryRouter } from 'react-router-dom';

export { Link, Switch, Redirect, Route } from 'react-router-dom';

export const Router = MemoryRouter;
```

Every import in the code should point to the `Router` instead of `react-router-native`.

**Comment by Kaltsoon** [comment]
@sahilrajput03 when you have time, could you try the fix that I just introduced at the end of the [Platform specific code](https://github.com/Kaltsoon/react-native-material/blob/master/material/2-react-native-basics.md#platform-specific-code) section:

**Comment by sahilrajput03** [comment]
Sure, gonna try it now only.

**Comment by Kaltsoon** [comment]
Build seems to work but `Link` components are broken. Both builds should export the `Link` component from the `react-router-native`, but this won't work because imports from `react-router-native` in the web environment are broken

**Comment by sahilrajput03** [comment]
Okay I'll check it too, will tell if that works anyhow..

**Comment by sahilrajput03** [comment]
I"m gonna try that via a hack though.

**Comment by sahilrajput03** [comment]
Also, instead of exporting as :

```
import { MemoryRouter } from 'react-router-dom';

export * from 'react-router-dom';

export const Router = MemoryRouter;
```

```
import { NativeRouter } from 'react-router-native';

export * from 'react-router-native';

export const Router = NativeRouter;
```

Using below syntax is oneliner and easy :
```
export * from 'react-router-dom'
export { MemoryRouter as Router } from 'react-router-dom'
```
and 
```
export * from 'react-router-dom'
export { NativeRouter as Router } from 'react-router-native';

```
What say?

**Comment by Kaltsoon** [comment]
Yes, that's better

**Comment by sahilrajput03** [comment]
![image](https://user-images.githubusercontent.com/31458531/89885491-c60f2b80-dbe8-11ea-9a1e-d420d8531a0b.png)
I don't know what happened but my web build is not running, I'm deleting node_modules and trying to install the project again. :(

**Comment by sahilrajput03** [comment]
yikes, installing node_modules again solved the issue, but I guess i terminated all node  applications from task managed did the real work. But its working now! :100:

**Comment by sahilrajput03** [comment]
![image](https://user-images.githubusercontent.com/31458531/89887913-bbef2c00-dbec-11ea-8e92-0804ccfed0a6.png)
Though the link is broken but changing the url works by hand works, I guess I'm missing something else to make it work!!

**Comment by sahilrajput03** [comment]
![myDebug](https://user-images.githubusercontent.com/31458531/89890463-0d99b580-dbf1-11ea-8dcc-0d522c9f01dc.gif)

Okay, I made it work by removing the component property, so what do we do now??
Also, * for web documentation tells to use React.forwardRef.  , idk why..?, Please figure it out, and see what can we do..
Src: https://reactrouter.com/web/api/Link/component-reactcomponent

**Comment by sahilrajput03** [comment]
i don't know how react.forward ref works clearly.., :( need to practise that first.

**Comment by sahilrajput03** [comment]
Okay, got it work but with a little hack! But it works great!!
![myDebug2](https://user-images.githubusercontent.com/31458531/89892138-d8db2d80-dbf3-11ea-930a-12e892f412c2.gif)


Actually I guess react-native and react-native-web wants us to use them different files, like AppBar.native.js and AppBar.web.js.
But in this gif, I have it worked just by hacking those only imports which i need, and it works great!

What say??
Thanks.!

**Comment by Kaltsoon** [comment]
Great that it works, but I find this a bit too hacky and complicated to be introduced in the material. In my opinion, saying that `react-router-native` will break the web preview and instruct to use other previews is enough for now.

**Comment by sahilrajput03** [comment]
Yup, I agree, its crappy workaround.
