### ISSUE TITLE
Wrong command in Exercise 10.1. - ESLint

### ISSUE THREAD

**Issue by miku86** [Kaltsoon/react-native-material#15]
Hey there,

in section [Exercise 10.1. - ESLint](https://github.com/Kaltsoon/react-native-material/blob/master/material/1-introduction-to-react-native.md#eslint), the text says:

> And finally, let's add a lint script to the package.json file to check the linting rules in specific files:

```
{
  "plugins": ["react"],
  "extends": ["eslint:recommended", "plugin:react/recommended"],
  "parser": "babel-eslint",
  "env": {
    "browser": true
  },
  "rules": {
    "react/prop-types": "off",
    "semi": "error"
  }
}
```

This seems to be the `.eslintrc` instead of a npm `lint` command.

**Comment by Kaltsoon** [comment]
Good catch, fixed it!
