### ISSUE TITLE
Error while updating property fontWeight in shadow node of type: RCTText; java.lang.Double cannot be cast to java.lang.string

### ISSUE THREAD

**Issue by sahilrajput03** [Kaltsoon/react-native-material#8]
```
import React from 'react';
import { Text, View } from 'react-native';

const BigBlueText = () => {
  return (
    <View style={{ padding: 20 }}>
      <Text style={{ color: 'blue', fontSize: 24, fontWeight: 700 }}>
        Big blue text
      <Text>
    </View>
  );
};
```
When using above snippet my device(redmi note 5) doens't open the my app on Expo app. Also, for a second it shows up the error and then exits the app to the Projects tab of the Expo app. Using screenshot I captured this-
![image](https://user-images.githubusercontent.com/31458531/89070237-57cd9c00-d392-11ea-93d7-e87c31783ca5.png)
So, the I figured it out, that it requires a string instead of int, and as expected by me, it works great with changing it to string!!!!
like:
```      <Text style={{ color: 'blue', fontSize: 24, fontWeight: "700"}}>```
Thanks.

**Comment by Kaltsoon** [comment]
Yes, it seems that valid options are `enum('normal', 'bold', '100', '200', '300', '400', '500', '600', '700', '800', '900')`. Thanks for pointing out, I'll fix these!
